### ISSUE TITLE
[Rule] Create URIRule

### ISSUE THREAD

**Issue by bigfoot90** [bigfoot90/phpacto#10]
`URIRule` should match 
- path parameters *(eg.* `/holidays/{name}/show` *)*
  where `{name}` can be any `Rule`
- and query parameters *(eg.* `/holidays?cat={category}` *)*
  where `{category}` can be any `Rule`

**Comment by bigfoot90** [comment]
Proposed Yaml representation:
```yaml
'@rule': uri
location: /holidays/{name}/show
parameters:
    name: 'A' #Can be a value or a Rule
    category: 'B' #Can be a value or a Rule
``` 
If a parameter is present in `location` string, then it **must** be declared in `parameters` array too.
The remaing parameters will compound the query string.

This Rule created like in the example above
 will mattch strings like `/holiday/A/show?category=B`
